[package]
name = "first"
version = "0.1.0"
authors = ["sofyan48 <sofyan.saputra@ralali.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1.41"
rand = "0.7.3"
